# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ruby Zheng
tagline:          A personal website
url:              http://www.rubyzheng.com
paginate:         1
baseurl:          /
author:
  name:           Ruby Zheng
  url:            http://www.rubyzheng.com
  email:          zhengsan@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/silveruby/silveruby.github.io
